language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name ${CONFIG_USERNAME}
  - git config user.email ${CONFIG_EMAIL}
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${github_token}@${GH_REF}" master:master

branches:
  only:
    - hexo

# 环境变量，把相应的键值改为你自己的就行了
env:
 global:
   - CONFIG_USERNAME: TonyJavaZ
   - CONFIG_EMAIL: uljjmhn520@gmail.com
   - GH_REF: github.com/uljjmhn520/uljjmhn520.github.io.git