version: "2.1"
volumes:
  source:
    driver: local
    driver_opts:
      type: none
      device: $PWD
      o: bind
services:
  hexo-blog:
    image: "lopydev/hexo"
    container_name: "hexo_blog"
    ports:
      - 50000:4000
    volumes:
      - source:/app